"""Migration Message

Revision ID: 0e5f7b8ddb9b
Revises: 2f88bed0a6eb
Create Date: 2024-11-28 16:29:03.352866

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5f7b8ddb9b'
down_revision: Union[str, None] = '2f88bed0a6eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isMakingFirstDeposit', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('isMakingFirstDeposit')

    # ### end Alembic commands ###
