"""Migration Message

Revision ID: 2f88bed0a6eb
Revises: 8ff3a910165a
Create Date: 2024-11-28 15:29:41.900396

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f88bed0a6eb'
down_revision: Union[str, None] = '8ff3a910165a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matrix_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matrix_users', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('position')

    # ### end Alembic commands ###
