"""add last interest earning time column to stake table

Revision ID: 6b6cae16f40a
Revises: 6598ddda2941
Create Date: 2024-11-30 12:50:11.507268

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b6cae16f40a'
down_revision: Union[str, None] = '6598ddda2941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stakings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastEarningTime', postgresql.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stakings', schema=None) as batch_op:
        batch_op.drop_column('lastEarningTime')

    # ### end Alembic commands ###
